[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.localnet]
socratic_token = "5AhcUJj8WtAqR6yfff76HyZFX7LWovRZ1bcgN9n3Rwa7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -r ts-node/register -t 1000000 tests/doc-chat.ts"
